spring:
  datasource:
    url: jdbc:sqlite:downloader.db
    driver-class-name: org.sqlite.JDBC
    username: sa
    password:
  jpa:
    database-platform: com.example.downloader.config.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %cyan([%thread]) %yellow(%logger{36}) - %msg%n"
  level:
    root: INFO
    com.example.downloader: INFO
    org.springframework.web: WARN
    org.apache.http: WARN